export interface Interview {
    interviewId:       number;
    date:              Date;
    candidateId:       number;
    candidateName:     string;
    candidateLastName: string;
    candidateEmail:    string;
    workerId:          number;
    workerEmail:       string;
    type:              string;
}

// Generated by https://quicktype.io

export interface ListInterview {
    fromDate:    string;
    toDate:      string;
    candidateId: number;
    workerId:    number;
    type:        string;
    paging:      Paging;
    sortOrder:   SortOrder;
}

export interface Paging {
    pageSize:   number;
    pageNumber: number;
}

export interface SortOrder {
    sort: Sort[];
}

export interface Sort {
    key:   string;
    value: string;
}
