// Generated by https://quicktype.io

export interface Recruitment {
    id:                  number;
    beginningDate:       string;
    endingDate:          string;
    name:                string;
    description:         string;
    recruiterId:         number;
    candidateCount:      number;
    recruitmentPosition: string;
    localization:        string;
    seniority:           string;
    hiredCount:          number;
    skills:              Skill[];
}

export interface Skill {
    skillId:    number;
    name:       string;
    skillLevel: number;
}


// Generated by https://quicktype.io

export interface RecruitmentList {
    totalCount:             number;
    recruitmentDTOs:        RecruitmentDTO[];
    recruitmentFiltringDTO: RecruitmentFiltringDTO;
    sortOrder:              SortOrder;
    paging:                 Paging;
}

export interface Paging {
    pageSize:   number;
    pageNumber: number;
}

export interface RecruitmentDTO {
    id:                  number;
    beginningDate:       Date;
    endingDate:          Date;
    name:                string;
    description:         string;
    recruiterId:         number;
    candidateCount:      number;
    recruitmentPosition: string;
    localization:        string;
    seniority:           string;
    hiredCount:          number;
}

export interface RecruitmentFiltringDTO {
    name:          string;
    description:   string;
    showOpen:      boolean;
    showClosed:    boolean;
    beginningDate: Date;
    endingDate:    Date;
    showPrivate:   boolean;
}

export interface SortOrder {
    sort: Sort[];
}

export interface Sort {
    key:   string;
    value: string;
}


