// Generated by https://quicktype.io

export interface Recruitment {
    // id:                  number;
    beginningDate:       string;
    endingDate:          string;
    name:                string;
    description:         string;
    recruiterId:         number;
    recruitmentPosition: string;
    localization:        string;
    seniority:           string;
    isPublic:            boolean;
    skills:              SkillsForProjectId[];
}

export interface Skill {
    id:    number,
    name:       string,
    skillLevel: number,
}

export interface SkillsForProjectId {
    skillId: number;
    skillLevel: number;
  }


// Generated by https://quicktype.io

export interface RecruitmentList {
    totalCount:             number;
    readRecruitmentDTOs:        RecruitmentDTO[];
    recruitmentFiltringDTO: RecruitmentFiltringDTO;
    sortOrder:              SortOrder;
    paging:                 Paging;
}

export interface Paging {
    pageSize:   number;
    pageNumber: number;
}

export interface RecruitmentDTO {
    id:                  number;
    beginningDate:       Date;
    endingDate:          Date;
    name:                string;
    description:         string;
    recruiterId:         number;
    candidateCount:      number;
    recruitmentPosition: string;
    localization:        string;
    seniority:           string;
    hiredCount:          number;
}

export interface RecruitmentFiltringDTO {
    name:          string;
    description:   string;
    showOpen:      boolean;
    showClosed:    boolean;
    beginningDate: Date;
    endingDate:    Date;
    showPrivate:   boolean;
}

export interface SortOrder {
    sort: Sort[];
}

export interface Sort {
    key:   string;
    value: string;
}

export interface GetRecruitmentListBodyRequest {
    name: string,
    description: string,
    beginningDate: string,
    endingDate: string,
    paging: {
      pageSize: number,
      pageNumber: number,
    },
    sortOrder: {
      sort: [
        {
          key: string,
          value: string
        }
      ]
    }
}


