// Generated by https://quicktype.io

export interface Skill {
  id: number,
  name: string,
  skillLevel: number
}

export interface SkillsForProjectId {
  skillId: number;
  // name: string;
  skillLevel: number;
}
