// Generated by https://quicktype.io

export interface User {
    id:         number;
    email:      string;
    userStatus: string;
    roleName:   string;
}


// Generated by https://quicktype.io

export interface UsersList {
    email:      string;
    userStatus: string;
    roleName:   string;
    paging:     Paging;
    sortOrder:  SortOrder;
}

export interface Paging {
    pageSize:   number;
    pageNumber: number;
}

export interface SortOrder {
    sort: Sort[];
}

export interface Sort {
    key:   string;
    value: string;
}
